dist: bionic

language: go
arch:
 - amd64
 - ppc64le
go:
  - 1.13
  - 1.14
  - 1.15

env:
  - GO111MODULE=on

script:
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
